export const REQUEST_FORISMATIC = "REQUEST_FORISMATIC";
export const DISPLAY_FORISMATIC = "DISPLAY_FORISMATIC";
export const REQUEST_RON = "REQUEST_RON";
export const DISPLAY_RON = "DISPLAY_RON";
export const REQUEST_FOAAS = "REQUEST_FOAAS";
export const DISPLAY_FOAAS = "DISPLAY_FOAAS";
export const REQUEST_DOG = "REQUEST_DOG";
export const DISPLAY_DOG = "DISPLAY_DOG";
